<?php
//SA 22 March 2017 deploy production
function getCombos($target) {
    $options = array(array(),array());
    $counter = count($target);
    foreach ($target as $loop) {
        if ($counter == count($target)) {
            $all = '';
            foreach ($target as $curr) {
                $all .= $curr.' ';
            }
            $all = substr($all, 0, strlen($all)-1);
            array_push($options[0], $all);
            array_push($options[1], findWhatsLeft($target, $all));
        } else if ($counter == 1) {
            foreach($target as $item) {
                array_push($options[0], $item);
                array_push($options[1], findWhatsLeft($target, $item));
            }
        } else if ($counter == 2) {
            foreach ($target as $item1) {
                foreach ($target as $item2) {
                    if ($item1 != $item2) {
                        if (!in_array($item1.' '.$item2, $options[0]) && !in_array($item2.' '.$item1, $options[0])) {
                            array_push($options[0], $item1.' '.$item2);
                            array_push($options[1], findWhatsLeft($target, $item1.' '.$item2));
                        }
                    }
                }
            }
        }
        $counter--;
    }
    array_push($options[0], '');
    array_push($options[1], findWhatsLeft($target, ''));    
    return $options;
}

function findWhatsLeft ($target, $current) {
    $current = explode(' ', $current);
    $leftOvers = '';
    foreach ($target as $currentTerm) {
        if (!in_array($currentTerm, $current)) {
            $leftOvers .= $currentTerm . ' ';
        }
    }
    return $leftOvers;
}

//die();
//echo $leftOvers;
//IMPORTANT Discuss with Casey SA 17 Jan 2017 needs to address url generated by td 4 which goes to local server
require_once('simple_html_dom.php');

$output = '';

//$semester = ['201701','201705'];
//$college = 'AP';
//$department = 'COM';
//$courseTitle = 'news';

if (isset($_REQUEST['searchSemesterKey'])) {
    $semester = $_REQUEST['searchSemesterKey'];
}

//SA 31 March 2017
$deliveryMethod4 = '';

if (isset($_REQUEST['deliveryMethod4'])) {
    $deliveryMethod4 = $_REQUEST['deliveryMethod4'];
}
//Apparently in OASIS delivery method is 4 not W
//echo $deliveryMethod4;
//SA 31 March 2017

if (isset($_REQUEST['searchTypeKey'])) {
    switch ($_REQUEST['searchTypeKey']) {
        case 'typed' :


            $userSearch = $_REQUEST['searchTermKey']; 
            $searchPhrase = explode(' ', $userSearch);
            $currentSemester =
            $collegeAbbreviation =
            $crnNumber =
            $courseNumber =
            $titleInstructorValue =
            $creditValue = '';

            $wildCards = array();
            $dptOrSubjValue = array();



            foreach ($searchPhrase as $segmentedTerm) {
                $originalTerm = $segmentedTerm;
                $segmentedTerm = str_split($segmentedTerm);
                $digitCount = 0;
                $letterCount = 0;
                foreach ($segmentedTerm as $currentChar) {
                    if (is_numeric($currentChar)) {
                        $digitCount++;
                    } else {
                        $letterCount++;
                    }
                }

                //echo $originalTerm . '(Digit Count: '.$digitCount.') (Letter Count: '.$letterCount.')<br>';

                if ($digitCount == 5 && $letterCount == 0) {
                    $crnNumber = $originalTerm;
                } else if ($digitCount == 4 && $letterCount == 0) {
                    $courseNumber = $originalTerm;
                } else if ($digitCount == 3 && $letterCount == 0) {
                    $sectionNumber = $originalTerm;
                } else if ($digitCount >= 1 && $digitCount <= 2 && $letterCount == 0) {
                    $creditValue = $originalTerm;
                } else if ($digitCount == 0 && $letterCount == 2) {
                    $collegeAbbreviation = $originalTerm;
                } else if ($digitCount == 0 && $letterCount == 3) {
                    array_push($dptOrSubjValue, $originalTerm);
                } else {
                    array_push($wildCards, $originalTerm);
                }
            }
            break;
    }
}

$wildCardCombos = getCombos($wildCards);
$titleValue = '';
$instructorValue = '';
$resultCount = 0; 
$dptOrSubjValuePos = 0;

$finalOutput = '';

$renderedContent = oasis ($semester, $wildCardCombos, $titleValue, $instructorValue, $resultCount, $dptOrSubjValue, $dptOrSubjValuePos, $crnNumber, $courseNumber, $sectionNumber, $creditValue, $collegeAbbreviation, $deliveryMethod4, $finalOutput);

function oasis (
    $semester,
    $wildCardCombos,
    $titleValue,
    $instructorValue,
    $resultCount,
    $dptOrSubjValue,
    $dptOrSubjValuePos,
    $crnNumber,
    $courseNumber,
    $sectionNumber,
    $creditValue,
    $collegeAbbreviation,
    $deliveryMethod4,
    $finalOutput
) {

    $dptOrSubjRealValue = $dptOrSubjValue[$dptOrSubjValuePos];

    $dptOrSubjValuePos++;

    foreach ($semester as $currentSemester) {

        for ($i = 0; $i < count($wildCardCombos[0]); $i++) {

            $titleValue = $wildCardCombos[0][$i];
            $instructorValue = $wildCardCombos[1][$i];

            $skip = false;

            /*
            if ($titleValue == '' && $instructorValue == '') {
                $skip = true;
            }
            */

            if (!$skip) {

                $curl = curl_init();

                curl_setopt_array($curl, array(
                    CURLOPT_VERBOSE => true,
                    CURLOPT_RETURNTRANSFER => 1,
                    CURLOPT_USERAGENT => 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 7.0; InfoPath.3; .NET CLR 3.1.40767; Trident/6.0; en-IN)',
                    CURLOPT_URL => 'https://usfonline.admin.usf.edu/pls/prodss/wp_staff_search_db',
                    CURLOPT_POST => 1,
                    CURLOPT_POSTFIELDS => array(
                        'P_SEMESTER' => $currentSemester,
                        'P_COL' => '',
                        'P_DEPT' => '',
                        //'P_DEPT' => $departmentValue,
                        'p_day_x' => 'no_val',
                        'p_day' => 'no_val',
                        'P_SESSION' => '',
                        'P_CAMPUS' => '',
                        'P_DIST' => $deliveryMethod4,
                        'p_status' => '',
                        'p_ssts_code' => 'A',
                        'P_CRSE_LEVL' => '',
                        'P_REF' => $crnNumber,
                        'P_SUBJ' => $dptOrSubjRealValue,
                        'P_NUM' => $courseNumber,
                        'P_TITLE' => trim($titleValue),
                        'P_CR' => $creditValue,
                        'P_TIME1' => '',
                        'P_INSTRUCTOR' => trim($instructorValue),
                        'P_UGR' => ''
                    )
                ));

                $info = curl_getinfo($curl);
                $resp = curl_exec($curl);
                curl_close($curl);

                $html = str_get_html($resp);
                $colCount = 0;
                
                $currentCourseTitle = '';
                $printoutItem = '';
                       
                foreach($html->find('#results td') as $element) {

                    switch ($colCount) {
                        case 0 :
                           $resultCount++;
                            $session =      $element->innertext;
                            break;
                        case 1 :
                            $col =          $element->innertext;
                            break;
                        case 2 :
                            $dpt =          $element->innertext;
                            break;
                        case 3 :
                            $crn =          $element->innertext;
                            break;
                        case 4 :
                            foreach($element->find('a') as $linkElement) {
                                $subjAndNum = explode('&nbsp;', $linkElement->innertext);
                                $subj = $subjAndNum[0];
                                $num = $subjAndNum[1];
                                //$num = '<a href="https://usfonline.admin.usf.edu'.$linkElement->href.'">'.$linkElement->innertext.'</a>'; 
                            }
                            break;
                        case 5 :
                            $sec =              $element->innertext;
                            break;
                        case 6 :
                            $type =             $element->innertext;
                            break;
                        case 7 :
                            $title =            $element->innertext;
                            $additionalInfo =   '';
                            $tempTitle = explode('<br>', $title);
                            for ($j = 0; $j < count($tempTitle); $j++) {
                                if ($j == 0) {
                                    $title = $tempTitle[$j];
                                } else {
                                    $additionalInfo .= $tempTitle[$j];
                                }
                            }
                            break;
                        case 8 :
                            $credits =          $element->innertext;
                            break;
                        case 9 :
                            $pmt =              $element->innertext;
                            break;
                        case 10 :
                            $status =           $element->innertext;
                            break;
                        case 12 :
                            $seatsRemain =      $element->innertext;
                            break;
                        case 13 :
                            $waitSeatsAvail =   $element->innertext;
                            break;
                        case 14 :
                            $cap =              $element->innertext;
                            break;
                        case 15 :
                            $enrl =             $element->innertext;
                            break;
                        case 16 :
                            $days =             $element->innertext;
                            break;
                        case 17 :
                            $time =             $element->innertext;
                            break;
                        case 18 :
                            $bldg =             $element->innertext;
                            break;
                        case 19 :
                            $room =             $element->innertext;
                            break;
                        case 20 :
                            $instructor =       $element->innertext;
                            break;     
                        case 21 :
                            $campus =           $element->innertext;
                            break;  
                        case 22 :
                            $deliveryMethod =   $element->innertext;
                            break;  
                        case 23 :
                            $fees =             $element->innertext;
                            break;
                    }

                    $colCount++;

                    $printoutItem++;

                    if ($colCount == 24) {
                        $colCount = 0;

                        $printout .= '

                            <ul id="'.$currentSemester.$subj.$num.'" data-semester="'.$currentSemester.'" data-subject="'.$subj.'" data-crs="'.$num.'">
                                
                                <li><strong>'.$subj . ' ' . $num . ': ' . $title.' ('.$credits.' Credits)</strong></li>
                                <li><strong>College/Department:</strong> '.$col . '/' . $dpt . '</li>

                                <li>'.$enrl.' students have enrolled. The cap is '.$cap.', and there are '.$seatsRemain.' seats remaining. '.$waitSeatsAvail.' wait seats are available.</li>

                                <br>
                                <button id="information'.$printoutItem.'" name="information'.$printoutItem.'" data-course-details="information'.$printoutItem.'" class="course-details btn btn-default btn-md">More Information</button>
                                <span></span>
                                <br>
     
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>session:</strong> '.$session.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>crn:</strong> '.$crn.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>sec:</strong> '.$sec.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>type:</strong> '.$type.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>pmt:</strong> '.$pmt.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>status:</strong> '.$status.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>days:</strong> '.$days.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>time:</strong> '.$time.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>bldg:</strong> '.$bldg.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>room:</strong> '.$room.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>instructor:</strong> '.$instructor.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>campus:</strong> '.$campus.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>deliveryMethod:</strong> '.$deliveryMethod.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>fees:</strong> '.$fees.'</li>
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>additionalInfo:</strong> '.$additionalInfo.'</li>

                                <br>
                            </ul>

                        ';

                    }
                }
            }
        }
    }

    $finalOutput .= $printout;

    if ($dptOrSubjValuePos < count($dptOrSubjValue)) {
        return oasis ($semester, $wildCardCombos, $titleValue, $instructorValue, $resultCount, $dptOrSubjValue, $dptOrSubjValuePos, $crnNumber, $courseNumber, $sectionNumber, $creditValue, $collegeAbbreviation, $deliveryMethod4, $finalOutput);
    } else {
        return '<h6>'.$resultCount.' '.$userSearch.' result(s) found.</h6>' . $finalOutput;
    }

}

echo $renderedContent;

?>