<?php
//SA 12 April deploy to online.usfsp.edu 
/////////////////////////////////////////////////// 
function getCombos($target) {
    $options = array(array(),array());
    $counter = count($target);
    foreach ($target as $loop) {
        if ($counter == count($target)) {
            $all = '';
            foreach ($target as $curr) {
                $all .= $curr.' ';
            }
            $all = substr($all, 0, strlen($all)-1);
            array_push($options[0], $all);
            array_push($options[1], findWhatsLeft($target, $all));
        } else if ($counter == 1) {
            foreach($target as $item) {
                array_push($options[0], $item);
                array_push($options[1], findWhatsLeft($target, $item));
            }
        } else if ($counter == 2) {
            foreach ($target as $item1) {
                foreach ($target as $item2) {
                    if ($item1 != $item2) {
                        if (!in_array($item1.' '.$item2, $options[0]) && !in_array($item2.' '.$item1, $options[0])) {
                            array_push($options[0], $item1.' '.$item2);
                            array_push($options[1], findWhatsLeft($target, $item1.' '.$item2));
                        }
                    }
                }
            }
        }
        $counter--;
    }
    array_push($options[0], '');
    array_push($options[1], findWhatsLeft($target, ''));    
    return $options;
}

function findWhatsLeft ($target, $current) {
    $current = explode(' ', $current);
    $leftOvers = '';
    foreach ($target as $currentTerm) {
        if (!in_array($currentTerm, $current)) {
            $leftOvers .= $currentTerm . ' ';
        }
    }
    return $leftOvers;
}

//die();
//echo $leftOvers;
//IMPORTANT Discuss with Casey SA 17 Jan 2017 needs to address url generated by td 4 which goes to local server
require_once('simple_html_dom.php');

$output = '';

//$semester = ['201701','201705'];
//$college = 'AP';
//$department = 'COM';
//$courseTitle = 'news';

if (isset($_REQUEST['searchSemesterKey'])) {
    $semester = $_REQUEST['searchSemesterKey'];
}

$deliveryMethod4 = '';

if (isset($_REQUEST['deliveryMethod4'])) {
    $deliveryMethod4 = $_REQUEST['deliveryMethod4'];
}
//SA April 2017 deliveryMethod is suffixed with 4 as a reminder OASIS delivery method is 4 not W

if (isset($_REQUEST['searchTypeKey'])) {
    switch ($_REQUEST['searchTypeKey']) {
        case 'typed' :


            $userSearch = $_REQUEST['searchTermKey']; 
            $searchPhrase = explode(' ', $userSearch);
            $currentSemester =
            $collegeAbbreviation =
            $crnNumber =
            $courseNumber =
            $titleInstructorValue =
            $creditValue = '';

            $wildCards = array();
            $dptOrSubjValue = array();



            foreach ($searchPhrase as $segmentedTerm) {
                $originalTerm = $segmentedTerm;
                $segmentedTerm = str_split($segmentedTerm);
                $digitCount = 0;
                $letterCount = 0;
                foreach ($segmentedTerm as $currentChar) {
                    if (is_numeric($currentChar)) {
                        $digitCount++;
                    } else {
                        $letterCount++;
                    }
                }

                //echo $originalTerm . '(Digit Count: '.$digitCount.') (Letter Count: '.$letterCount.')<br>';

                if ($digitCount == 5 && $letterCount == 0) {
                    $crnNumber = $originalTerm;
                } else if ($digitCount == 4 && $letterCount == 0) {
                    $courseNumber = $originalTerm;
                } else if ($digitCount == 3 && $letterCount == 0) {
                    $sectionNumber = $originalTerm;
                } else if ($digitCount >= 1 && $digitCount <= 2 && $letterCount == 0) {
                    $creditValue = $originalTerm;
                } else if ($digitCount == 0 && $letterCount == 2) {
                    $collegeAbbreviation = $originalTerm;
                } else if ($digitCount == 0 && $letterCount == 3) {
                    array_push($dptOrSubjValue, $originalTerm);
                } else {
                    array_push($wildCards, $originalTerm);
                }
            }
            break;
    }
}

$wildCardCombos = getCombos($wildCards);
$titleValue = '';
$instructorValue = '';
$resultCount = 0; 
$dptOrSubjValuePos = 0;

$finalOutput = '';

$renderedContent = oasis ($semester, $wildCardCombos, $titleValue, $instructorValue, $resultCount, $dptOrSubjValue, $dptOrSubjValuePos, $crnNumber, $courseNumber, $sectionNumber, $creditValue, $collegeAbbreviation, $deliveryMethod4, $finalOutput);

function oasis (
    $semester,
    $wildCardCombos,
    $titleValue,
    $instructorValue,
    $resultCount,
    $dptOrSubjValue,
    $dptOrSubjValuePos,
    $crnNumber,
    $courseNumber,
    $sectionNumber,
    $creditValue,
    $collegeAbbreviation,
    $deliveryMethod4,
    $finalOutput
) {

    $dptOrSubjRealValue = $dptOrSubjValue[$dptOrSubjValuePos];

    $dptOrSubjValuePos++;

    foreach ($semester as $currentSemester) {

        for ($i = 0; $i < count($wildCardCombos[0]); $i++) {

            $titleValue = $wildCardCombos[0][$i];
            $instructorValue = $wildCardCombos[1][$i];

            $skip = false;

            /*
            if ($titleValue == '' && $instructorValue == '') {
                $skip = true;
            }
            */

            if (!$skip) {

                $curl = curl_init();

                curl_setopt_array($curl, array(
                    CURLOPT_VERBOSE => true,
                    CURLOPT_RETURNTRANSFER => 1,
                    CURLOPT_USERAGENT => 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 7.0; InfoPath.3; .NET CLR 3.1.40767; Trident/6.0; en-IN)',
                    CURLOPT_URL => 'https://usfonline.admin.usf.edu/pls/prodss/wp_staff_search_db',
                    CURLOPT_POST => 1,
                    CURLOPT_POSTFIELDS => array(
                        'P_SEMESTER' => $currentSemester,
                        'P_COL' => '',
                        'P_DEPT' => '',
                        //'P_DEPT' => $departmentValue,
                        'p_day_x' => 'no_val',
                        'p_day' => 'no_val',
                        'P_SESSION' => '',
                        'P_CAMPUS' => '',
                        'P_DIST' => $deliveryMethod4,
                        'p_status' => '',
                        'p_ssts_code' => 'A',
                        'P_CRSE_LEVL' => '',
                        'P_REF' => $crnNumber,
                        'P_SUBJ' => $dptOrSubjRealValue,
                        'P_NUM' => $courseNumber,
                        'P_TITLE' => trim($titleValue),
                        'P_CR' => $creditValue,
                        'P_TIME1' => '',
                        'P_INSTRUCTOR' => trim($instructorValue),
                        'P_UGR' => ''
                    )
                ));

                $info = curl_getinfo($curl);
                $resp = curl_exec($curl);
                curl_close($curl);

                $html = str_get_html($resp);
                $colCount = 0;
                
                $currentCourseTitle = '';
                $printoutItem = '';
                       
                foreach($html->find('#results td') as $element) {

                    switch ($colCount) {
                        case 0 :
                           $resultCount++;
                            $session =      $element->innertext;
                            break;
                        case 1 :
                            $col =          $element->innertext;
                            break;
                        case 2 :
                            $dpt =          $element->innertext;
                            break;
                        case 3 :
                            $crn =          $element->innertext;
                            break;
                        case 4 :
                            foreach($element->find('a') as $linkElement) {
                                $subjAndNum = explode('&nbsp;', $linkElement->innertext);
                                $subj = $subjAndNum[0];
                                $num = $subjAndNum[1];
                                //$num = '<a href="https://usfonline.admin.usf.edu'.$linkElement->href.'">'.$linkElement->innertext.'</a>'; 
                            }
                            break;
                        case 5 :
                            $sec =              $element->innertext;
                            break;
                        case 6 :
                            $type =             $element->innertext;
                            break;
                        case 7 :
                            $title =            $element->innertext;
                            $additionalInfo =   '';
                            $tempTitle = explode('<br>', $title);
                            for ($j = 0; $j < count($tempTitle); $j++) {
                                if ($j == 0) {
                                    $title = $tempTitle[$j];
                                } else {
                                    $additionalInfo .= $tempTitle[$j];
                                }
                            }
                            break;
                        case 8 :
                            $credits =          $element->innertext;
                            break;
                        case 9 :
                            $pmt =              $element->innertext;
                            break;
                        case 10 :
                            $status =           $element->innertext;
                            break;
                        case 12 :
                            $seatsRemain =      $element->innertext;
                            break;
                        case 13 :
                            $waitSeatsAvail =   $element->innertext;
                            break;
                        case 14 :
                            $cap =              $element->innertext;
                            break;
                        case 15 :
                            $enrl =             $element->innertext;
                            break;
                        case 16 :
                            $days =             $element->innertext;
                            break;
                        case 17 :
                            $time =             $element->innertext;
                            break;
                        case 18 :
                            $bldg =             $element->innertext;
                            break;
                        case 19 :
                            $room =             $element->innertext;
                            break;
                        case 20 :
                            $instructor =       $element->innertext;
                            break;     
                        case 21 :
                            $campus =           $element->innertext;
                            break;  
                        case 22 :
                            $deliveryMethod =   $element->innertext;
                            break;  
                        case 23 :
                            $fees =             $element->innertext;
                            break;
                    }

                    $colCount++;

                    $printoutItem++;

                    $percentEnroll = $enrl/$cap;
                    $percentWait = $waitSeatsAvail;
                    $numberToShow = number_format( $percentEnroll * 10, 0 );
                    $numberToWait = number_format( $percentWait * 10, 0 );

//////////////////////////////////
//SA 12 April 2017
//SA double check the need for foreach in next three code blocks
                    $countM = (substr_count($days, 'M'));

                    if ($countM == 1 ) {
                        $showDay[0]  =  "background-color:white;color:green;";
                    }
    
                    $countT = (substr_count($days, 'T'));
                    if ($countT == 1 ) {
                        $showDay[1]  =  "background-color:white;color:green;";
                    }
    

                   $countW = (substr_count($days, 'W'));
                    if ($countW == 1 ) {
                        $showDay[2]  =  "background-color:white;color:green;";
                    }
    
                    $countR = (substr_count($days, 'R'));
                    if ($countR == 1 ) {
                        $showDay[3]  =  "background-color:white;color:green;";
                    }
    
                    $countF = (substr_count($days, 'F'));
                    if ($countF == 1 ) {
                        $showDay[4]  =  "background-color:white;color:green;";
                    }
    
                    $countS = (substr_count($days, 'S'));
                    if ($countS == 1 ) {
                        $showDay[5]  =  "background-color:white;color:green;";
                    }
    

                   $countU = (substr_count($days, 'U'));
                    if ($countU == 1 ) {
                        $showDay[6]  =  "background-color:white;color:green;";
                    }
    
//SA 12 April 2017
//////////////////////////////////
             $countShow = array(

                        $countShow[0],
                        $countShow[1],
                        $countShow[2],
                        $countShow[3],
                        $countShow[4],
                        $countShow[5],
                        $countShow[6],
                        $countShow[7],
                        $countShow[8],
                        $countShow[9]
                        );

                $countTheShow = count($countShow);

                foreach ($countShow as $loopItem) {               

                        for ($x = 0; $x <= $countTheShow; $x++) {      
                            if ($x <= $numberToShow) {
                            $show[$x]  =   'color:#009374;';
                            } else {
                            $show[$x]  =   'color:#000;';   
                            }//closes else 

                        }//for           
                    }//foreach            
          
//////////////////////////////////
             $countWait = array(

                        $countWait[0],
                        $countWait[1],
                        $countWait[2],
                        $countWait[3],
                        $countWait[4],
                        $countWait[5],
                        $countWait[6],
                        $countWait[7],
                        $countWait[8],
                        $countWait[9]
                        );

                $countTheWait = count($countWait);

                foreach ($countWait as $loopItem) {               

                        for ($x = 0; $x <= $countTheWait; $x++) {      
                            if ($x <= $numberToWait) {
                            $wait[$x]  =   'color:#009374;';
                            } else {
                            $wait[$x]  =   'color:#000;';   
                            }//else 

                            if ($x == 0) {
                            $wait[$x]  =   'color:#000;'; 
                            }
                    }//for           
                }//foreach            
          
////////////////////////////////////              

                    if ($colCount == 24) {
                        $colCount = 0;

                        $printout .= '
                        <div class="row panel panel-default">
                            <section class="panel-body">

                            <ul id="'.$currentSemester.$subj.$num.'" data-semester="'.$currentSemester.'" data-subject="'.$subj.'" data-crs="'.$num.'">
                                <li><h3><strong>'.$subj . ' ' . $num . ': ' . $title.' ('.$credits.' Credits)</strong></h3></li>
                                <li><h4><strong>College/Department:</strong> '.$col . '/' . $dpt . '</h4></li>


                                <br>
                                <button id="information'.$printoutItem.'" name="information'.$printoutItem.'" data-course-details="information'.$printoutItem.'" class="course-details btn btn-success btn-md">More Information</button>
                                <span></span>
                                <br>
                                <div class="col-md-6">

                                <section class="information'.$printoutItem.'">
                                    <li class="information'.$printoutItem.'" style="display:none;margin-top:10px;" data-course-details="information'.$printoutItem.'"><strong>
                                         <span class="weekday padding-5" style="'.$showDay[0].'" aria-label="Monday">Mo</span>
                                         <span class="weekday padding-5" style="'.$showDay[1].'" aria-label="Tuesday">Tu</span>
                                         <span class="weekday padding-5" style="'.$showDay[2].'" aria-label="Wednesday">We</span>
                                         <span class="weekday padding-5" style="'.$showDay[3].'" aria-label="Thursday">Th</span>
                                         <span class="weekday padding-5" style="'.$showDay[4].'" aria-label="Friday">Fr</span>
                                         <span class="weekday padding-5" style="'.$showDay[5].'" aria-label="Saturday">Sa</span>
                                         <span class="weekday padding-5" style="'.$showDay[6].'" aria-label="Sunday">Su</span>
                                         </strong></li>
                                    <li class="information'.$printoutItem.'" style="display:none;margin-top:20px;" data-course-details="information'.$printoutItem.'"><strong>session:</strong> '.$session.'</li>
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>days:</strong> '.$days.'</li>
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>time:</strong> '.$time.'</li>
                                </section><br />


                                <section class="information'.$printoutItem.'">
                                <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'">
                                    <span style="'.$show[0].'" class="'.$countShow[0].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    <span style="'.$show[1].'" class="'.$countShow[1].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    <span style="'.$show[2].'" class="'.$countShow[2].' glyphicon glyphicon-user" aria-hidden="true"></span>   
                                    <span style="'.$show[3].'" class="'.$countShow[3].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    <span style="'.$show[4].'" class="'.$countShow[4].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    <span style="'.$show[5].'" class="'.$countShow[5].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    <span style="'.$show[6].'" class="'.$countShow[6].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    <span style="'.$show[7].'" class="'.$countShow[7].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    <span style="'.$show[8].'" class="'.$countShow[8].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    <span style="'.$show[9].'" class="'.$countShow[9].' glyphicon glyphicon-user" aria-hidden="true"></span><br />

                                    '.$enrl.' students have enrolled.<br /> The cap is '.$cap.', and there are '.$seatsRemain.' seats remaining.
                                </li>
                                </section><br />

                                <section class="information'.$printoutItem.'">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'">
                                        <span style="'.$wait[0].'" class="'.$countWait[0].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span style="'.$wait[1].'" class="'.$countWait[1].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span style="'.$wait[2].'" class="'.$countWait[2].' glyphicon glyphicon-user" aria-hidden="true"></span>   
                                        <span style="'.$wait[3].'" class="'.$countWait[3].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span style="'.$wait[4].'" class="'.$countWait[4].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span style="'.$wait[5].'" class="'.$countWait[5].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span style="'.$wait[6].'" class="'.$countWait[6].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span style="'.$wait[7].'" class="'.$countWait[7].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span style="'.$wait[8].'" class="'.$countWait[8].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                        <span style="'.$wait[9].'" class="'.$countWait[9].' glyphicon glyphicon-user" aria-hidden="true"></span>
                                    </li>    
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>'.$waitSeatsAvail.' </strong>Wait seats are available.</li>
                                </section><br />


                                <section class="information'.$printoutItem.'" style="margin-top:5px;">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><strong>additionalInfo:</strong> '.$additionalInfo.'</li>
                                </section>

                                 </div>

                                <div class="col-md-6">

                                <section class="information'.$printoutItem.'">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>campus:</strong> '.$campus.'</span></h4></li>
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>bldg:</strong> '.$bldg.'</span></h4></li>
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>room:</strong> '.$room.'</span></h4></li>
                                </section>

                                <section class="information'.$printoutItem.'" style="margin-top:10px;">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>fees:</strong> '.$fees.'</span></h4></li>
                                </section>


                                <section class="information'.$printoutItem.'" style="margin-top:5px;">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>pmt:</strong> '.$pmt.'</span></h4></li>
                                </section>

                                <section class="information'.$printoutItem.'" style="margin-top:5px;">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>crn:</strong> '.$crn.'</span></h4></li>
                                </section>

                                <section class="information'.$printoutItem.'" style="margin-top:5px;">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>status:</strong> '.$status.'</span></h4></li>
                                </section>

                                <section class="information'.$printoutItem.'" style="margin-top:5px;">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>sec:</strong> '.$sec.'</span></h4></li>
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>type:</strong> '.$type.'</span></h4></li>
                                </section>                      

                                <section class="information'.$printoutItem.'" style="margin-top:5px;">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>deliveryMethod:</strong> '.$deliveryMethod.'</span></h4></li>
                                </section>

                                <section class="information'.$printoutItem.'" style="margin-top:5px;">
                                    <li class="information'.$printoutItem.'" style="display:none;" data-course-details="information'.$printoutItem.'"><h4><span class="label label-default"><strong>instructor:</strong> '.$instructor.'</span></h4></li>
                                </section>



                                </div>
                                <br>
                            </ul>
                            </section>
                          </div>  
                        ';

                    }
                }
            }
        }
    }


    $finalOutput .= $printout;

    if ($dptOrSubjValuePos < count($dptOrSubjValue)) {
        return oasis ($semester, $wildCardCombos, $titleValue, $instructorValue, $resultCount, $dptOrSubjValue, $dptOrSubjValuePos, $crnNumber, $courseNumber, $sectionNumber, $creditValue, $collegeAbbreviation, $deliveryMethod4, $finalOutput);
    } else {
        return '<h4>'.$resultCount.' '.$userSearch.' result(s) found.</h4>' . $finalOutput;
    }

}

echo $renderedContent;

?>